---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: default
provisioner: nfs-storage
parameters:
  archiveOnDelete: "true"
mountOptions:
  - "local_lock=all"
